import '../../rakelib/Rakefile'
import '../baseimage/Rakefile'

require 'platform'

task :default => [ :build, 'docker:test' ]
task :build => 'banshee:build'

namespace :banshee do
  @user = `whoami`.strip
  desc 'Set image name and build'
  task :build => 'ubuntu_baseimage:build' do
    @name='banshee'
    Rake::Task['docker:build'].reenable
    Rake::Task['docker:build'].invoke(:buildargs => { 'user' => @user })
  end

  desc 'Enter container as current user'
  task :run do
    os = Gem::Platform::local.os
    if os == "linux"
      display = "unix" + ENV['DISPLAY']
    elsif os == "darwin"
      ip = `ifconfig | grep \"inet \" | grep -v 127.0.0.1 | grep -v \"broadcast 0.0.0.0\" | awk '{print $2}'`.strip
      display = "#{ip}\:0"
    end
    system "docker run -it "\
      "-u #{@user} "\
      "-w /home/#{@user} "\
      "-e DISPLAY=#{display} "\
      "-v ${HOME}/code:/home/#{@user}/code "\
      "-v ${HOME}/Music:/home/#{@user}/Music "\
      "-v ${HOME}/.config/banshee-1:/home/#{@user}/.config/banshee-1 "\
      "-v /tmp/.X11-unix:/tmp/.X11-unix "\
      "--device /dev/snd "\
      "rucker/banshee:latest"
    begin
      image = Docker::Image.get("rucker/banshee:latest")
    rescue
      task = Rake::Task['docker:banshee:build']
      task.reenable
      task.invoke
    end
  end
end
