require 'docker'
require 'rake'
require 'rspec/core/rake_task'

@group = 'rucker'
@name = nil

task :default => 'docker:test'
namespace :docker do
  
  desc 'Run specs'
  RSpec::Core::RakeTask.new(:spec) do |t|
    t.pattern = Dir.glob('spec/*_spec.rb')
    t.rspec_opts = '--format documentation'
    t.rspec_opts << ' --color'
  end
  
  desc 'Remove dangling docker images'
  task :cleanup do
    images = `docker images -q -f dangling=true`
    system "docker rmi #{images}" unless images.empty?
  end
  
  task :test => [
    :spec,
    :cleanup
  ]
  
  desc 'Build docker image'
  task :build, [:args] do |t, args|
    #TODO What should happen if user invokes rake docker:build?
    unless @name.nil?
      opts = { 't' => "#{@group}/#{@name}:latest" }
      unless args.to_a.empty? or args['args'][:buildargs].empty?
        opts = opts.merge({ 'buildargs' => args['args'][:buildargs].to_json })
      end
      Docker::Image.build_from_dir('.', opts)
    end
  end
end
